name: build and checks
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12"]
        env:
            USING_COVERAGE: "3.12"
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4.1.5
            - name: Set up Python
              uses: actions/setup-python@v5.1.0
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: make deps
            - name: Check pep8
              run: |
                  python -m flake8 --max-complexity 10 --max-line-length 100 --ignore D --extend-ignore E203,W503 blank_project/
                  python -m flake8 --max-complexity 10 --max-line-length 100 --ignore D --extend-ignore E203,W503,F401 tests/
            - name: Check code style
              run: |
                  python3 -m black --line-length 100 --check blank_project/
                  python3 -m black --line-length 100 --check tests/
            - name: Check imports
              run: |
                  python3 -m isort -c -v blank_project/
                  python3 -m isort -c -v tests/
            - name: Check types
              run: python3 -m mypy --install-types --non-interactive blank_project
            - name: Check docstrings
              run: python3 -m pydocstyle blank_project/
            - name: Run tests
              run: make tests-cov-json
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v4.3.1
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                file: ./coverage.json
                flags: unittests
                verbose: true
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
